### ISSUE TITLE
Need to add text on how to download the config files for newcomers

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#143]
Just a small change for the get started page. When you click on config.txt or config.ini, it brings you to the text file itself and doesn't offer to download it. I know how to download it myself, but newcomers will be confused by this and not realize that you can right click and save link as. What can be done is have a bit of text on the side that reminds users that they need to right click and save link as. Trust me, there are some really dense people that don't know how to do something as simple as that. I got the idea when someone asked about it on discord a few mins ago.

**Comment by Plailect** [comment]
Actually I intentionally did not mention it because those links were *supposed* to have the html `download` attribute so they wouldn't have to do it manually, but it appears kramdown isn't recognizing that specific attribute so it is not being applied. I'll try to fix it, but if I can't I'll just do your suggestion.

**Comment by Plailect** [comment]
I think this was fixed with the last commit. It downloads the file when I click the link using Chrome, though I have not tested with other browsers the `download` attribute should be compatible with most modern browsers. This issue can be re-opened if there are still issues.
