### ISSUE TITLE
Multiple issues gathered together in an all-in-one post

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#80]
I've decided to pull all the issues into one post that I've gathered over time. Be prepared to read a lot. Consider it a documentation, something I kept editing as time went on. The issues are the main things to tackle, the suggestions below are just optional ideas.

**Text updated 8-17-17**

**Issues**

**Issue # 1  - 5.5.2 users Need Haxchi**
This one was already reported recently, but I'll explain anyways. 5.5.2 users were once hopeless with no way to access Homebrew. Now that there's a new exploit, it's so unstable that it's only worth using for installing Haxchi. But the guide does not prepare the user for Haxchi installation for 5.5.2 users. If you boot into HBL on 5.5.2 without a DS VC game and Haxchi files on the SD, you've basically wasted your time. They need Homebrew Launcher, the Haxchi setup files, and a DS VC game like Brain Age (USA) **($6.99)** or Dr Kawashima (EUR) **(6.29£)** **installed on NAND**. By default Eshop installs games to USB if one is inserted. Also if they have DNS setup beforehand, they won't be able to get into Eshop on 5.5.2. So the first step is to buy the DS VC game from Eshop, then the 5.5.2 exploit to install Haxchi, and finally setup the DNS.

**Issue # 2 - 5.5.2 CBHC users cannot use loadiine.ovh to install Homebrew Launcher Channel**
This issue is referring to the **Homebrew Launcher Channel** section of the guide. Basically when you have CBHC, you're gonna need HBL Channel to enter Homebrew Launcher. But using the browser to install that on 5.5.2 wouldn't be ideal since loadiine.ovh doesn't work. Instead, during the bootup process when "Autobooting" is displayed on the gamepad, they must press HOME. Then they can simply choose Homebrew Launcher from the CBHC menu and then use Wup installer GX2 to install the HBL Channel. **The guide currently has users use the browser to go to loadiine.ovh but doesn't take account of 5.5.2 users.** In general, it's easier to not use the browser and just use the CBHC menu to get into Homebrew Launcher. Believe it or not, you can actually launch the "DO NOT TOUCH ME!" Icon and that will also launch the CBHC menu where you can load up Homebrew Launcher just the same.

**Issue # 3 - Incorrect title for one of the compatible DS VC games for Haxchi**
I've noticed the abscense of Brain Age on the list of compatible games, the cheapest DS VC for USA users. Meanwhile Dr Kawashima's Brain Training, the EUR version surely is on the list. Instead there's "Big Brain Training" Which is a game that doesn't even exist. It seems like you've mixed up "**Big** Brain Academy", "**Brain** Age", and "Dr Kawashima's Brain **Training**" into one name. Users would be unsure what game to buy in USA and often ask while confused.

**Issue # 4 - No Homebrew Launcher download in vWii guide**
So the vWii guide has you download Wuphax for use on the Wii U Homebrew Launcher. But it doesn't provide a download to Homebrew Launcher itself. Not even on the Homebrew Launcher page that's linked at the start of the vWii guide. You cannot boot up Wuphax without having Homebrew Launcher on the SD card. It should be listed as a download right alongside Wuphax.

**Issue # 5 - vWii guide doesn't instruct users to install the HBC Forwarder**
It's been known since as far back as 2012, that when you launch Homebrew Channel it will display in 4:3 aspect ratio because vWii thinks it's a VC game. But there's a Homebrew Channel Forwarder, which is a .wad you can install which has 16:9 support. This has always been the final touch of all previous vWii guides. You can find the forwarder channel [HERE](http://www.hacksden.com/showthread.php/7814-Workaround-for-the-HBC-with-the-latest-Wii-U-update)
The user also needs [YAWMM (Yet Another Wad Manager)](http://www.hacksden.com/attachment.php?attachmentid=793&d=1369548542) to install the wad file. 
It's completely up to you if you want to add another section for this in the vWii guide. Else people will have to deal with the 4:3 homebrew channel.

---------------------------------------------

**Ideas/Suggestions** (These are optional suggestions to consider)

**Idea/suggestion # 1 - Create a portal after "Get Started" to pick a firmware**
There can be a portal similar to 3ds.guide which would display a pool of different firmware ranges, leading to different things depending on their firmware. Like for example, there can be a 1.0 - 5.4 section that will lead to a page showing how to update to 5.5.1 via disc update with certain games. Then a 5.5.1 section and a 5.5.2 section. The first step of the 5.5.2 section would be to get a DS VC and setup haxchi. While the 5.5.1 section would use the guide as usual.

**Idea/suggestion # 2 - Add a Q&A**
It would be really useful if there were an Q&A section that answers many basic questions. This can be linked on top and even at the end of the guide for the user to learn some things if they choose to.

**Idea/Suggestion # 3 - Need a guide to remove the update folder to futureproof users**
This can be added as an additional guide such as your **A9LH to B9S** guide that sits on top of the page. Deleting the system's update folder has proven to prevent any form of system updates. The update folder can be recreated at any time just like any ordinary folder. I just think it's extremely useful to create a worry free setup where the user cannot possibly mess up later on. Basically you just need Ftpiiu Everywhere and an FTP client, and CFW enabled. If using Mocha, get Diimok's Ftpiiu Everywhere and if using Haxchi/CBHC, get FIX94's release. Once connected to the wii u through FTP, the user can browser to "**root/storage_mlc/sys/**" and delete the **update folder**. I know what you're thinking, "Users are too dumb and they can't be trusted with a simple task such as deleting one empty folder". It's literally the easiest thing to do and it's super effective.

-------------------------------------------------------

***Extra notes***

- WUP Installer GX2 has a random chance of crashing with a "Dsi Exception has occured" error screen. This is a very small chance of happening and it should be noted to shut down the console and try again if this occured while using WUP Installer GX2 (Or any WUP Installer really)

- It would seem that opening the browser's curtains helps the success rate of the 5.5.2 exploit.

- Another thing to note is the HIGH amount of reports of users getting **FSGetMountSource Failed**. There could be anoher reminder during the 5.5.2 exploit that the SD needs to be FAT32 and inserted properly. And if using a micro SD card, the adapter may be faulty. This is a common issue aside from 5.5.2 users, and it's the biggest headache for users to deal with especially when it comes to using the 5.5.2 exploit. Imagine trying over 20 times just to finally get the exploit working, but you get **FSGetMountSource Failed**

**Comment by ghost** [comment]
Worth noting that currently users are reporting the most likely 5.5.2 exploit to succeed is the one at http://cg.stupiid.ovh/ on delta 4

**Comment by ghost** [comment]
Quick update, after some upstream developments, the http://stupiid.ovh/ (same as http://u.drg.li/) gateway is succeeding more than it's failing. ~~Personally, I got up to 15 successes in a row with delta 4.~~ Delta 0 seems to be the best one (it's also the default (big exploit button) on stupiid.ovh), but 4 also has a high success rate.

**Comment by Plailect** [comment]
@ColtonDRG Your git history is so messy that I honestly can't tell exactly what is different with your fork.

**Comment by Plailect** [comment]
@MattKimura Please split "Idea/Suggestion # 3" and the "FSGetMountSource error" into their own separate issues. I'll fix those later.

**Comment by ghost** [comment]
Yeah, sorry about that. I did not proofread my commits. My fork contains mostly the following interesting things:

- A more user friendly index
- A delta selection system making use of the Server Side Includes feature of nginx, so the delta can be selected using exploit.html?delta=# instead of manually altering the exploit.html file for each delta.

My `gh-pages` branch contains the following further alterations:

- Compatibility with GitHub pages by regressing the features that require Server Side Includes
- Seperate delta#.html files for each delta since the other delta selection feature was regressed.

The reason the `gh-pages` branch exists is mainly because we discovered by some experimentation that in earlier versions of the exploit, it might have been more reliable if the exploit was very specifically hosted on GitHub and then passed through Cloudflare's CDN _without_ going through GitHub's own Fastly CDN. For this reason I named it the cg method (**c**loudflare>**g**ithub). Now that the exploit is more reliable, I'm not sure this sort of thing is necessary, but it definitely seemed like it was helping our chances before that.

Also, on the issue of the browser curtains, we mostly speculated that it helped because I personally got it to work many times with them opened but never with them closed. Since the new version of the exploit came out, I have gotten it to work many more times with the curtains both opened and closed. There is still a possibility that it has some effect on things, but it seems to me that it might have just been random chance and I got unlucky when I had them closed. Even when we first started talking about the curtains, my best guess for why it would make any difference was because more processing power was being spent on rendering the curtain models and the animated Mii on the top screen, and that seemed pretty far fetched.

Last thing, deltas 0 and 4 seem more reliable than 2 with the current version of the exploit. I always will make the big exploit button use the one that currently seems the most reliable, so perhaps the guide should be updated to tell users to use that one.
